language: c++

# for regular CI, we don't need the submodules
git:
  submodules: false

matrix:
  include:
    - name: Ubuntu xenial (x86_64) debug
      environment: BUILD_TYPE=Debug
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - zlib1g-dev
      script: bash -xe ci/build-nix.sh

    - name: Ubuntu xenial (x86_64) release
      environment: BUILD_TYPE=Release
      dist: xenial
      addons:
        apt:
          update: true
          packages:
            - libsdl2-dev
            - libsdl2-image-dev
            - libsdl2-mixer-dev
            - zlib1g-dev
      script: bash -xe ci/build-nix.sh

    - name: macOS (x86_64) debug
      environment: BUILD_TYPE=Debug
      os: osx
      addons:
        homebrew:
          packages:
            - sdl2
            - sdl2_image
            - sdl2_mixer
            - glew
          update: true
      script: bash -xe ci/build-mac.sh

    - name: Windows (x86_64) debug (crossbuild from Ubuntu bionic x86_64, MinGW-w64)
      environment: BUILD_TYPE=Debug
      dist: bionic
      addons:
        apt:
          update: true
          packages:
            - mingw-w64
      script: bash -xe ci/build-win-cross.sh
